### ISSUE TITLE
Phonetic search for names

### ISSUE THREAD

**Issue by jkoshy** [TechForPalestine/palestine-datasets#107]
The ability to search for names phonetically (e.g., with [Soundex](https://en.wikipedia.org/wiki/Soundex)) would make these databases much more accessible to non-Arabic speakers.

I found a mapping of Arabic characters to Soundex codes here: https://www.codeproject.com/Articles/26880/Arabic-Soundex/  Could this perhaps be used as a starting point?

**Comment by sterlingwes** [comment]
I'm not familiar with soundex, are you suggesting someone should be able to say the name into their microphone and have it pull up the closest arabic match?

**Comment by sterlingwes** [comment]
If I understand the problem, I think the simplest approach here would be to come up with a dictionary of similar name spellings and have the existing translated English name search tool treat them as aliases.

**Comment by sterlingwes** [comment]
Got it, thanks for clarifying. I still think capturing alternate spellings or including the transliterated variant in the existing frontend fuzzy search would be a quicker way to see an improvement here. Maybe not as robust as what you propose but I don't have time to implement a whole backend search feature.

I'll leave this issue open in case anyone is interested in digging into it on their own time

**Comment by jkoshy** [comment]
The problem with using alternate lists of Latin spellings is that the number of transliterations needed increases combinatorially.

A back-of-the-envelope computation: sites on the 'net with lists of baby names list about a thousand 'popular' Arabic first names.  Each name seem to have 3 to 4 syllables, and each syllable could be encoded in Latin script in 2 to 3 ways: e.g., "Zuleikha" could use "Zu" or "Su", "lei" "lay" "ley" or "li", "kha" or "ka", and so on.

So, for just for 'popular' first names, we would have to maintain:

  1000 names ✕ 3.5 syllables on average ✕ 2.5 encoding choices per syllable on average ≅ 8750 alternate Latin spellings.

Even with the 8.7✕ increase of maintenance effort such a list would still be incomplete - it would not cover surnames or the less popular first names.

**Comment by sterlingwes** [comment]
I'm not sure I follow - the library I linked would do transliteration for the original arabic name, which is a separate tactic from the "alternate spellings" approach. You wouldn't have to transliterate the alternate latin spellings, they're just another alias for the existing translated english name. If your concern is that someone might not be able to type the alternate spellings properly I think the existing fuzzy search algo we're using on the frontend will accommodate that reasonably well. Again, these are all just broad strategies, we'd need some prototyping and concrete scenarios to test against.

**Comment by 1palestine** [comment]
Could utilize Elasticsearch/OpenSearch

It offers great tokenizers for stuff like this.

https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-phonetic.html

**Comment by 1palestine** [comment]
But yea, Phonetic searches cannot be done statically. It would require a backend that allows these various datasets to work together. A raw HTTP request for JSON won't cut it.

**Comment by sterlingwes** [comment]
Thanks @1palestine that's good to know! I'm not sure there's a big need for this yet, but if we get that feedback I'd certainly be open to exploring more complicated infra to achieve improvements here

**Comment by sterlingwes** [comment]
Confirmed recently after adding some tracking to the site that the current search tool isn't used much (clicks amount to <0.45% of impressions on the biggest day). This is with a week's worth of tracking, so will keep an eye on it and reopen if it seems like something we should revisit & pitch to the org for funding / hosting
