### ISSUE TITLE
I'm very weird!

### ISSUE THREAD

**Issue by mwalid207** [TechForPalestine/palestine-datasets#184]
Maybe Microsoft one day take an alarm from **Isreal** then **delete** all these repos and all this data in seconds :/

**Comment by sterlingwes** [comment]
Hey @mwalid207 👋🏻  It's a valid concern for sure. I have a copy of the repository and so do other developers judging by the fork count, so I'm not too concerned about losing work here. Thanks for raising though, you're not weird!
