### ISSUE TITLE
Potential data inaccuracy in infrastructure data endpoint

### ISSUE THREAD

**Issue by Good-Shepherd-Collective** [TechForPalestine/palestine-datasets#238]
`{
"report_date": "2024-05-13",
"civic_buildings": {
"destroyed": 186,
"ext_destroyed": 186
},
"educational_buildings": {
"destroyed": 103,
"ext_destroyed": 103,
"damaged": 311,
"ext_damaged": 311
},
"places_of_worship": {
"mosques_destroyed": 247,
"ext_mosques_destroyed": 247,
"mosques_damaged": 326,
"ext_mosques_damaged": 326,
"churches_destroyed": 3,
"ext_churches_destroyed": 3
},
"residential": {
"destroyed": 86000,
"ext_destroyed": 86000
}
},
{
"report_date": "2024-05-14",
"civic_buildings": {
"ext_destroyed": 187
},
"educational_buildings": {
"ext_destroyed": 104,
"ext_damaged": 311
},
"places_of_worship": {
"ext_mosques_destroyed": 604,
"ext_mosques_damaged": 200,
"ext_churches_destroyed": 3
},
"residential": {
"ext_destroyed": 86200
}
},
{
"report_date": "2024-05-15",
"civic_buildings": {
"ext_destroyed": 187
},
"educational_buildings": {
"ext_destroyed": 105,
"ext_damaged": 312
},
"places_of_worship": {
"ext_mosques_destroyed": 604,
"ext_mosques_damaged": 200,
"ext_churches_destroyed": 3
},
"residential": {
"ext_destroyed": 86400
}
},`

It is unclear to me why `ext_mosques_damaged` would suddenly decrease in number

https://data.techforpalestine.org/api/v3/infrastructure-damaged.json

Keep up the good work everyone.

**Comment by sterlingwes** [comment]
Hey @Good-Shepherd-Collective thanks for flagging this

We noted something similar in our doc page: https://data.techforpalestine.org/docs/infrastructure-damaged/

Namely:

> * Note that the distribution of destroyed vs. damaged mosques shifted considerably in May. In their May 18th report, the number of mosques classified as destroyed sharply increased, while the number classified as damaged decreased. It's unclear whether this is due to reporting difficulties, delays, or a change in classification approach.

Does that help clarify?

**Comment by Good-Shepherd-Collective** [comment]
Yikes. Sorry I didn't notice that comment. That makes complete sense. You folks are doing great work. In solidarity from Palestine!
