### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by pbiggar** [TechForPalestine/palestine-datasets#264]
Someone asked me could they use this data for their project, and I checked and I don't see any LICENSE file or setting in GH or on the website. Could we add some? The closest I see is MIT license in package.json, but it's unclear whether that applies to the data or the code.

**Comment by sterlingwes** [comment]
Good call - I went with "The Unlicense" which is the closest I could find to releasing our work to the public domain, hope that works!
