### ISSUE TITLE
Entries with age fields that are probably wrong

### ISSUE THREAD

**Issue by alvii147** [TechForPalestine/palestine-datasets#297]
Hello,

From the payload of the [Killed in Gaza endpoint](https://data.techforpalestine.org/docs/killed-in-gaza/), I found three entries where the age doesn't make sense:

```
       id dob  age                           en_name
400198651     1994 Saif-al-islam Jamal Khamis Ashour
800136673     1983 Emad Muhammad Rafat Jodt Abdrabah
917525198     1962       Hasanat Jodt Faraj Abdrabah
```

I'm guessing these are actually birth years?

**Comment by sterlingwes** [comment]
Thanks for raising this issue, all fixed
