### ISSUE TITLE
do have python addon

### ISSUE THREAD

**Issue by mrTaha28** [TechForPalestine/palestine-datasets#302]
is there an "import" for python to import commands to python or javascript

**Comment by sterlingwes** [comment]
hi @mrTaha28 we don't have an SDK or library if that's what you mean. We provide an API you can request data from using those languages. We've linked a python API example someone shared in our examples page: https://data.techforpalestine.org/docs/examples/

**Comment by sterlingwes** [comment]
You don't have to use it as an API, you could write python script similar to how they're requesting JSON from our pages:
https://github.com/ummahrican/palestine-api/blob/93cab4a9d5c99574e48fd1d4afc7d0e02b82c3d7/main.py#L4-L16
