### ISSUE TITLE
Add Hind's Banner to example usage section

### ISSUE THREAD

**Issue by alvii147** [TechForPalestine/palestine-datasets#321]
Hi there, I've recently created some banners in my repository, [Hind's Banner](https://github.com/alvii147/hinds-banner), some of which use the datasets in this repository to display the total number of Palestinians killed:

```md
[![Free Palestine](https://hinds-banner.vercel.app/free-palestine?variant=olive)](https://www.pcrf.net/)
``` 

[![Free Palestine](https://hinds-banner.vercel.app/free-palestine?variant=olive)](https://www.pcrf.net/)

```md
[![Genocide Watch](https://hinds-banner.vercel.app/genocide-watch?variant=olive)](https://www.pcrf.net/)
```

[![Genocide Watch](https://hinds-banner.vercel.app/genocide-watch?variant=olive)](https://www.pcrf.net/)

Can this be added to the example usage section please?

**Comment by alvii147** [comment]
Happy to also open the pull request for the changes.

**Comment by sterlingwes** [comment]
Absolutely! Thank you for sharing

**Comment by sterlingwes** [comment]
updated the site and added to our readme 🙏🏻  feel free to open if you have any additional feedback
